### PR TITLE
fix: cleanup timer and reuse exports

### LINKED ISSUE #228: @sentry/profiling-node crashes vitest
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/node

### SDK Version

7.92.0

### Framework Version

vitest any

### Link to Sentry event

_No response_

### SDK Setup

```js
import * as SentryApi from '@sentry/node';
// Edit an assertion and save to see HMR in action
import { ProfilingIntegration } from '@sentry/profiling-node';

SentryApi.init({
  integrations: [new ProfilingIntegration()],
});

```

### Steps to Reproduce

I tried to setup a minimal repro here: https://stackblitz.com/edit/vitest-dev-vitest-1gd3e9?file=src%2Fsentry.ts

but I failed, because profiling integration does not run on stackblitz. 
So what you need to do:
 1. download from stackblitz
 2. extract
 3. pnpm i
 4. pnpm test
 5. hit enter to restart the tests for few seconds(10 times probably+-)

### Expected Result

Vitest does not crash

### Actual Result

vitest crashes after a few runs
[Screencast from 5.1.2024 17:53:35.webm](https://github.com/getsentry/sentry-javascript/assets/1305378/2374622c-5a07-40f7-a0f5-b3d9d84741f6)

### PR DESCRIPTION
**Pull request by JonasBa**
Fix #228 (tested by linking the built module to the reproducible code from issue).

### CODE REVIEW

File: bindings/cpu_profiler.cc [hunk 1]
```diff
@@ -1060,22 +1069,15 @@ napi_value Init(napi_env env, napi_value exports) {
 
   Profiler *profiler = new Profiler(env, isolate);
 
-  if (napi_set_instance_data(env, profiler, NULL, NULL) != napi_ok) {
-    napi_throw_error(env, nullptr, "Failed to set instance data for profiler.");
-    return NULL;
-  }
-
-  napi_value external;
-  if (napi_create_external(env, profiler, nullptr, nullptr, &external) !=
```
Comment (JonasBa) [inline bindings/cpu_profiler.cc:1069]: this was unnecessary since NAPI_INIT provides the exports napi_value already

File: bindings/cpu_profiler.cc [hunk 2]
```diff
@@ -1049,6 +1038,26 @@ static napi_value StopProfiling(napi_env env, napi_callback_info info) {
...
 };
 
+void FreeAddonData(napi_env env, void *data, void* hint) {
+  Profiler *profiler = static_cast<Profiler *>(data);
+
+  if(profiler == nullptr){
+    return;
+  }
+
+  if (profiler->active_profiles.size() > 0) {
```
Comment (anonrig) [inline bindings/cpu_profiler.cc:1048]:
```suggestion
  if (!profiler->active_profiles.empty()) {
```

File: bindings/cpu_profiler.cc [hunk 3]
```diff
@@ -1049,6 +1038,26 @@ static napi_value StopProfiling(napi_env env, napi_callback_info info) {
...
+    for (auto &profile : profiler->active_profiles) {
+      CleanupSentryProfile(profiler, profile.second, profile.first);
+    }
+  }
+
+  if(profiler->cpu_profiler != nullptr){
```
Comment (anonrig) [inline bindings/cpu_profiler.cc:1054]:
```suggestion
  if (profiler->cpu_profiler != nullptr){
```

**Comment by anonrig** [comment]
Somehow, we have a lint issue, but GitHub workflow doesn't give us a warning?

**Comment by JonasBa** [comment]
I'm going to check, it should be failing, but I also noticed some formatting changes were applied that shouldn't be

**Comment by JonasBa** [comment]
@anonrig let me fix the linter separately, I want to merge this so we fix the issue and unblock the user. I'll followup with the linter change

**Review by anonrig — APPROVED** [review]
